### PR TITLE
Fix/CON-238/reset settings in media after changing source

### PR DESCRIPTION
**Pull request by bziondik**
Related to: https://oat-sa.atlassian.net/browse/CON-238

Fixed reset of width in Media Interaction and object after changing source.

How to test:

- go to Item Authoring
- create Media Interaction and A-block with object contained video with width 50% for example
- save go to Items page
- return to item Authoring
- change source in Media Interaction(to audio) and object(to image)
- width should be reseted

### CODE REVIEW

**Comment by habemuscode** [comment]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by 404passionFruit — COMMENTED** [review]
Code looks good, will test locally

**Comment by 404passionFruit** [comment]
Audio worked fine, but there is weird behavior with wide image in A block.

When I create A block, the width of the wide image is 100%
Screenshot

But if I create A block with video and then change the source, the image overflows
Screenshot

**Comment by bziondik** [comment]
> Audio worked fine, but there is weird behavior with wide image in A block.
> 
> When I create A block, the width of the wide image is 100%
> Screenshot
> 
> But if I create A block with video and then change the source, the image overflows
> Screenshot

Looks like you use different icons, responsive mode for images will be in case left icon 
image and right icon has width/height for images

**Review by 404passionFruit — APPROVED** [review]

**Pull request merged**
