### PR TITLE
FIX/AUT-2088 Fix horizontal size choices

### PR DESCRIPTION
**Pull request by meefox**
1/2
Releated to [AUT-2088](https://oat-sa.atlassian.net/browse/AUT-2088)

**Description:**
Add handler to remove predefined height when switching from vertical to horizontal list in choices interaction.

**Changes:**
* Added reset height method that is setting the height to auto for previously set adapted heigh

**How to check:**
* Create a new item
* Add choices Interaction
* Add an inline image to the second option
* Check between vertical/horizontal mode
* Should not take more space anymore in horizontal mode

**Requires:**
* Require [tao-core](https://github.com/oat-sa/tao-core-sdk-fe/pull/144)

### CODE REVIEW

**Review by jsconan — COMMENTED** [review]
The code looks ok, but unfortunately, the behavior is sloppy.

After several changes between vertical and horizontal layout, the display is broken:
- horizontal image
- vertical image

**Review by jsconan — CHANGES_REQUESTED** [review]
Actually, the fix works pretty well, if we discard a case that may not be related to it.
But the linked package is wrong, please see the comment below.

Regarding the fix itself, it has a small glitch with the horizontal layout. It seems to reserve the space for the picture with its biggest size:
- image
- image

**Review by jsconan — APPROVED** [review]
It works nicely.
Good job!

Note: the sizing problem on the horizontal layout is not related to this change indeed. 
**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] ~~New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Review by btamas — APPROVED** [review]
It works as expected.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Comment by AntonNeviarouski** [comment]
QA verified

**Pull request merged**
