### PR TITLE
TAO-436: Prevent polygon shape to be resized

### PR DESCRIPTION
**Pull request by hutnikau**
Instead of resizing polyline shape will be transformed by moving the vertex.

### CODE REVIEW

**Comment by clawfire** [comment]
It's not working here :/ I got the same behavior than before. When I try to move a vertex the shape just reduce to 0x0. Is there's some commit missing or ... ?

**Comment by hutnikau** [comment]
I checked it and all is works fine. Which browser do you use? Maybe some js files was in cache?
6528a7ad6ed926a010b0122f7485806f

**Comment by clawfire** [comment]
I use Firefox 35.0.1 under osx. I have no cache and use the empty cache command just in case. Don't have this behavior. I'll ask another dev here to test it also ( poke @krampstudio )

**Comment by clawfire** [comment]
And it's works. Thx.

**Pull request merged**
