### PR TITLE
fix/AUT-1956/interaction-image-deletion-button-fixed

### PR DESCRIPTION
**Pull request by marpesia**
**Related to:** Regression with [AUT-1956](https://oat-sa.atlassian.net/browse/AUT-1956)
Related PRs:
- https://github.com/oat-sa/extension-tao-itemqti/pull/2056
- https://github.com/oat-sa/extension-tao-itemqti/pull/2070

**Description:**
Conflict with CSS rules between the two fixes above

**Changes:**

- Refactor CSS of the delete button on Choice and Order interaction. The goal is to support the remove button object on the prompt and on the item elements. Checked with image and Math element.

**How to check:**

- Verify that the AC on [AUT-1956](https://oat-sa.atlassian.net/browse/AUT-1956) and [AUT-1955](https://oat-sa.atlassian.net/browse/AUT-1955) are met.
image
image

**Composer** https://oat-sa.atlassian.net/browse/TR-3674?focusedCommentId=181025

**TAE** https://oat-sa.atlassian.net/browse/AUT-1956?focusedCommentId=181723

### CODE REVIEW

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on playground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by Silvia-loza — APPROVED** [review]
Just a small comment to check, trash icon in prompt shows to the right of img instead of the left...not sure if this is supposed to be like that or whether is part of this ticket?
Everything else works perfect! 
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Comment by marpesia** [comment]
Update: check horizontal and vertical interactions

**Review by bziondik — APPROVED** [review]

**Review by Silvia-loza — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Pull request merged**
