### PR TITLE
[Fix ADF 787] - Gap match trash icon shifted

### PR DESCRIPTION
**Pull request by habemuscode**
**Ticket**

https://oat-sa.atlassian.net/browse/ADF-787

### CODE REVIEW

**Comment by hectoras** [comment]
It works for me: The trash bin icon does not hide the input anymore. 

However, the "Add choice" icon is not aligned with the choices themselves (unsure if that was the case previously).
image

I think it can be fixed by setting `margin-top: 25px;` to the add-option CSS class to match the `margin-top` rule from `.edit-question .qti-blockInteraction .horizontal .qti-choice` (but keep in mind I'm just guessing -- I don't know if that would break things at other places).

**Review by clagosarias — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Review by adriloma — APPROVED** [review]
Code review only 
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits

**Review by hectoras — APPROVED** [review]

**Comment by AntonNeviarouski** [comment]
QA verified

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by marpesia — APPROVED** [review]

**Pull request merged**
