### PR TITLE
Added tabindex attributes to several interactions for proper work of …

### PR DESCRIPTION
**Pull request by Alroniks**
Related to https://oat-sa.atlassian.net/browse/TAO-1034

### CODE REVIEW

**Comment by Alroniks** [comment]
Rebased, because was conflict with this merged PR https://github.com/oat-sa/extension-tao-itemqti/pull/418

**Comment by krampstudio** [comment]
Would'nt it be better to have `tabindex="0"` so we can keep tabbing in the order of appearance.

**Comment by Alroniks** [comment]
Yes, I agree @krampstudio Updated PR

**Comment by krampstudio** [comment]
The inlineChoice interaction doesn't focus correctly : 
 - you have to tab 2 times
 - the style is not applied (the shady border)

**Comment by Alroniks** [comment]
@krampstudio which browser do you use? I've checked in Chrome and Firefox on Mac.

**Comment by krampstudio** [comment]
I'm able to reproduce with both.

**Comment by Alroniks** [comment]
Reverted 1 to 0 for tabindex.

**Comment by Alroniks** [comment]
Close for https://github.com/oat-sa/extension-tao-itemqti/pull/424

**Pull request closed without merging**
