### PR TITLE
[Fix] CON 122 - Graphic design match mockup

### PR DESCRIPTION
**Pull request by habemuscode**
**Issues**

https://oat-sa.atlassian.net/browse/CON-122

**Related issues**

https://github.com/oat-sa/tao-core-ui-fe/pull/230

**Mockup**

https://projects.invisionapp.com/d/main#/console/20371039/431571617/preview

**Fix**

- [x] **3. Add criteria button (in inline choice interaction)**: spacing between icon and label. Use the same look and feel as for the add choice button for drop downs.
- [x] **Bonus**: Center the icon

**Before**

imagen

**After**

imagen

### CODE REVIEW

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by wazelin — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful ⚠️ please specify what exactly is matching a mockup now
- [x] Pull request's target is not `master`

**Review by andrey-ponamarev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Comment by habemuscode** [comment]
Can be tested here: http://playground.kitchen.it.taocloud.org/?p=test-juan_delivery.git;a=summary

**Pull request merged**
