### PR TITLE
Tao 2766/flysystem item packer issues

### PR DESCRIPTION
**Pull request by boajer**
Depends on https://github.com/oat-sa/extension-tao-item/pull/224, https://github.com/oat-sa/extension-tao-testqti/pull/558, https://github.com/oat-sa/extension-tao-test/pull/140, https://github.com/oat-sa/extension-tao-devtools/pull/67

### CODE REVIEW

**Comment by bugalot** [comment]
@boajer 

Unfortunately unit tests are broken:

`PHP Fatal error:  Call to undefined method tao_models_classes_service_StorageDirectory::getPath() in /home/jerome/Development/TAO/taoplatform300/taoItems/models/classes/class.ItemCompiler.php on line 89
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   7. PHPUnit_Framework_TestCase->run() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
PHP   8. PHPUnit_Framework_TestResult->run() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
PHP  11. ReflectionMethod->invokeArgs() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  12. oat\taoQtiItem\test\ItemImportTest->testCompile() /home/jerome/Development/TAO/taoplatform300/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  13. taoItems_models_classes_ItemCompiler->compile() /home/jerome/Development/TAO/taoplatform300/taoQtiItem/test/ItemImportTest.php:266
PHP  14. taoItems_models_classes_ItemCompiler->getLanguageCompilationPath() /home/jerome/Development/TAO/taoplatform300/taoItems/models/classes/class.ItemCompiler.php:50`

**Comment by boajer** [comment]
@bugalot Could you take a look again please

**Comment by krampstudio** [comment]
The unit test returns me the following errors : 

```sh
sudo -u www-data php ./vendor/bin/phpunit --colors taoQtiItem/test/pack/QtiItemPackerTest.php 
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

...EEEEEEE.EE

Time: 131 ms, Memory: 9.00MB

There were 9 errors:

1) oat\taoItems\test\pack\QtiItemPackerTest::testPackingSimpleItem
common_Exception: Non QTI item(foo) opened via QTI Service

/home/bertrand/dev/projects/package-tao/taoQtiItem/model/qti/Service.php:113
/home/bertrand/dev/projects/package-tao/taoQtiItem/model/pack/QtiItemPacker.php:71
/home/bertrand/dev/projects/package-tao/taoQtiItem/test/pack/QtiItemPackerTest.php:126

2) oat\taoItems\test\pack\QtiItemPackerTest::testPackingItemResponseProcessing
common_Exception: Non QTI item(foo) opened via QTI Service

/home/bertrand/dev/projects/package-tao/taoQtiItem/model/qti/Service.php:113
/home/bertrand/dev/projects/package-tao/taoQtiItem/model/pack/QtiItemPacker.php:71
/home/bertrand/dev/projects/package-tao/taoQtiItem/test/pack/QtiItemPackerTest.php:165
......
```

**Comment by krampstudio** [comment]
You need also to retrieve the public directory during the [packItem call](https://github.com/oat-sa/extension-tao-itemqti/blob/9b14de8404ff26a01506c221f4cac6d62e086fba/model/pack/QtiItemPacker.php#L83),

otherwise we cannot run the following code : 

```php
$uri   = 'an item URI';

$packer = new Packer(new core_kernel_classes_Resource($uri));
$encoders =[
    'img' => 'base64file',
    'css' => 'base64file'
];
$pack = $packer->pack($encoders, false);

echo json_encode($pack, JSON_PRETTY_PRINT);
```

**Comment by krampstudio** [comment]
Maybe this can help : 

I'm using the following script to pack the items : https://gist.github.com/krampstudio/e5dd943f3f10afdce8622d230fa1d5c4

**Comment by krampstudio** [comment]
Feel free to re-assign the PR (I'll be in holidays next weeks, :palm_tree: )

**Comment by boajer** [comment]
@bugalot please review it again

**Comment by krampstudio** [comment]
While running a packing using https://gist.github.com/krampstudio/e5dd943f3f10afdce8622d230fa1d5c4 I have the following issue : 

```sh
PHP Warning:  The use statement with non-compound name 'core_kernel_classes_Resource' has no effect in /home/bertrand/dev/projects/package-tao/taoQtiItem/pack.php on line 11
PHP Catchable fatal error:  Argument 1 passed to oat\oatbox\filesystem\FileSystemHandler::setServiceLocator() must implement interface Zend\ServiceManager\ServiceLocatorInterface, null given, called in /home/bertrand/dev/projects/package-tao/taoItems/models/classes/pack/Packer.php on line 142 and defined in /home/bertrand/dev/projects/package-tao/vendor/zendframework/zend-servicemanager/src/ServiceLocatorAwareTrait.php on line 25
```

How can I set up the `ServiceLocator` ?

**Pull request merged**
