### PR TITLE
Fix [CON-203] - Color of arrowheads does not match with color of lines

### PR DESCRIPTION
**Pull request by habemuscode**
**Issue**

https://oat-sa.atlassian.net/browse/CON-203

**Related work**

https://github.com/oat-sa/extension-tao-itemqti/issues/1577

**Description**

The color of all arrowheads (including axis arrowheads) changes, when we change the current line or add new. So, it will always inherit the color from the last path created with the arrow-end/ arrow-start attribute set.
 
imagen

The full description of [issue](https://github.com/oat-sa/extension-tao-itemqti)/issues/1577

Also, it looks like the PCI settings are broken on the construct side. When trying to open Lines options an error pops up in the console.

imagen

**AC**

- [x] Fix arrow head color
- [ ] Fix error in console of PCI settings

### CODE REVIEW

**Review by bziondik — COMMENTED** [review]
I see also 2 places with `raphael.js` v2.1.2:
`tao/views/js/lib/raphael/raphael.js`
`taoQtiItem/views/js/legacyPortableSharedLib/raphael.js`
Should be they updated also?

**Comment by habemuscode** [comment]
@bziondik I check yesterday or the day before and all routes are pointing to `portableLib`, not legacy or other places, at least before build

**Comment by bziondik** [comment]
> @bziondik I check yesterday or the day before and all routes are pointing to `portableLib`, not legacy or other places, at least before build

Maybe, but why we can updated them
```
tao/views/js/lib/raphael/raphael.js
taoQtiItem/views/js/legacyPortableSharedLib/raphael.js
```
 also?

**Review by andrey-ponamarev — CHANGES_REQUESTED** [review]
Please, copy all changes directly from library sources without modification.
As I see it was fixed in `v2.2.2`
https://github.com/DmitryBaranovskiy/raphael/blob/v2.2.2/raphael.js#L5974
Could you check if we can use the latest version of the library?

**Comment by habemuscode** [comment]
Additional PR for tao -> https://github.com/oat-sa/tao-core/pull/2786

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by boajer — APPROVED** [review]
BE LGFM

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by 404passionFruit — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
