### PR TITLE
fix/AUT-560/tables added to passage not displayed in Authoring

### PR DESCRIPTION
**Pull request by focaloid-dev**
**Related Issue :** https://oat-sa.atlassian.net/browse/AUT-560 
If user added the Table via CK Editor to the Passage during it's authoring, this Table will not display if the passage containing it will be added to the item during Item Authoring.

**Preconditions**: Passage containing table is created.

**Steps to reproduce:**

- Go to Items tab.
- 
- Create a new item and go to it's authoring.
- 
- Add any interaction to the canvas.
- 
- Add a Passage containing Table to this interaction.

**Actual result:** The Passage is added, the Table is not displayed in Item Authoring page.
**Expected result:** The Passage is added, all of it's contend is displayed including Table.

Env : http://tao-test-alshoja.playground.kitchen.it.taocloud.org:46031/

### CODE REVIEW

**Review by Silvia-loza — COMMENTED** [review]
It looks good but we need to update the version of the extension [sem ver]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Comment by AntonNeviarouski** [comment]
QA verified on http://tao-test-alshoja.playground.kitchen.it.taocloud.org:46031/

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Pull request merged**
