### PR TITLE
Fix/aut-1979/handle-imported-items

### PR DESCRIPTION
**Pull request by shaveko**
related to https://oat-sa.atlassian.net/browse/AUT-1979

### Description

If item is authored using Terre feature set and then imported into authoring having Solar feature set, some of features are still visible in ui

https://oat-sa.atlassian.net/browse/AUT-1979?focusedCommentId=188272

This PR tend to fix :

 - Presence of shuffle buttons in UI of various interactions using SimpleChoice / InlineChoice component
 - Tooltip is displayed in the imported item with set-up tooltip

### How to test

- Setup authoring to Terre feature set 
(run command  
`php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_TAO_ADVANCE_ONLY -v false`
in fpm container and `redis-cli flushall` in redis container)

 - Create item with ChoiceInteraction, InlineChoice interaction, OrderInteraction, Match and enable choice shuffle

 - Create various interactions which have tooltips in prompts, A-blocks, choices
 
 - Setup authoring to Solar feature set (run command  
`php index.php 'oat\tao\scripts\tools\FeatureFlag\FeatureFlagTool' -s FEATURE_FLAG_TAO_ADVANCE_ONLY -v true`
in fpm container and `redis-cli flushall` in redis container)

 - check the interactions have no shuffle buttons and no tooltips which you have set up

### CODE REVIEW

**Review by meefox — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — COMMENTED** [review]
It works well for the shuffled choices.

For the tooltip, it is removed from the authoring, but when the item is in preview, the tooltips are visible.

image

**Comment by shaveko** [comment]
> It works well for the shuffled choices.
> 
> For the tooltip, it is removed from the authoring, but when the item is in preview, the tooltips are visible.
> 
> image

I assume that if Authoring is set up for Solar feature set, Solar preview is used. In solar preview they are not visible. Anyways now they are not being rendered neither in Authoring (Solar feature set) nor Solar preview (tao-item-runner-qtinui-fe)

**Review by jsconan — APPROVED** [review]
Look ok (except for the tooltip edge case which can be tackled later)

**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] ~~New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Comment by AntonNeviarouski** [comment]
QA verified

**Pull request merged**
