### PR TITLE
Fix/TR-2474/upload interaction RTL

### PR DESCRIPTION
**Pull request by olga-kulish**
Related to https://oat-sa.atlassian.net/browse/TR-2474

In RTL mode Upload interaction content should be aligned to the right

How to test:
- create an item, on item properties panel, in `Language` dropdown, choose `Arabic`
- publish a test with this item

### CODE REVIEW

**Review by svoronuk — APPROVED** [review]
Result a little bit unaligned with expected design

**Review by svoronuk — COMMENTED** [review]
Final version of design is differs from AC, but for me in LTR mode design is also strange) Could you confirm that current implementation acceptable?

**Comment by olga-kulish** [comment]
> 
> 
> Final version of design is differs from AC, but for me in LTR mode design is also strange) Could you confirm that current implementation acceptable?

I'll change it, current is wrong - in normal (LTR) mode 'Browse' button sticks to the main (left) side, so here it should also stick to main (right) one

**Review by oatymart — APPROVED** [review]
The result looks good. I can see that some of the styles you overrode (`.lft`, `1.42857%`...) were the result of strange practices, but let's not try to fix them now.

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Documentation is updated according to changes (if applicable)

**Review by svoronuk — APPROVED** [review]
Looks according to AC, good job! Of course values like `1.4%` looks strange, but i hope LTR design developed correctly.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Pull request merged**
