### PR TITLE
fix ItemImportTest unit test

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by antoinerobin** [comment]
what's the aim of this PR ? ItemImportService's unit test was already working

**Comment by hutnikau** [comment]
Yes, all tests passed but there is an error during execution of this test:
```
PHP Notice:  Trying to get property of non-object in D:\domains\package-tao\taoQtiItem\model\qti\metadata\imsManifest\ImsManifestMetadataExtractor.php on line 54
PHP Stack trace:
PHP   1. {main}() C:\Users\Oleg\AppData\Local\Temp\ide-phpunit.php:0
PHP   2. IDE_Base_PHPUnit_TextUI_Command::main() C:\Users\Oleg\AppData\Local\Temp\ide-phpunit.php:589
PHP   3. PHPUnit_TextUI_Command->run() C:\Users\Oleg\AppData\Local\Temp\ide-phpunit.php:299

PHP   4. PHPUnit_TextUI_TestRunner->doRun() D:\domains\package-tao\vendor\phpunit\phpunit\src\TextUI\Command.php:149
PHP   5. PHPUnit_Framework_TestSuite->run() D:\domains\package-tao\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:440
PHP   6. PHPUnit_Framework_TestCase->run() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestSuite.php:747
PHP   7. PHPUnit_Framework_TestResult->run() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestCase.php:724
PHP   8. PHPUnit_Framework_TestCase->runBare() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestResult.php:612
PHP   9. PHPUnit_Framework_TestCase->runTest() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestCase.php:768

PHP  10. ReflectionMethod->invokeArgs() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestCase.php:908


PHP  11. oat\taoQtiItem\test\ItemImportTest->testWrongManifest() D:\domains\package-tao\vendor\phpunit\phpunit\src\Framework\TestCase.php:908
Time: 4.91 seconds, Memory: 12.00MB

PHP  12. oat\taoQtiItem\model\qti\ImportService->importQTIPACKFile() D:\domains\package-tao\taoQtiItem\test\ItemImportTest.php:132

OK (13 tests, 51 assertions)
PHP  13. oat\taoAct\model\metadata\manifest\ActMetadataExtractor->extract() D:\domains\package-tao\taoQtiItem\model\qti\ImportService.php:288
PHP  14. oat\taoQtiItem\model\qti\metadata\imsManifest\ImsManifestMetadataExtractor->extract() D:\domains\package-tao\taoAct\model\metadata\manifest\ActMetadataExtractor.php:19

Process finished with exit code 0
```

**Comment by antoinerobin** [comment]
thank's it wasn't obvious. Can you please increment the version number ?

**Comment by hutnikau** [comment]
Done

**Pull request merged**
