### PR TITLE
AUT-1100 export passage included to PCI

### PR DESCRIPTION
**Pull request by pnal**
Related to: https://oat-sa.atlassian.net/browse/AUT-1100 (steps to reproduce can be found inside the ticket)

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
Have issues with item and test preview math PCI with passage with image (FE issue)
image

In delivery imported mathPCI with passage with image in base64 works
image
But original mathPCI with passage with image have wrong href
image

**Comment by pnal** [comment]
> Have issues with item and test preview math PCI with passage with image (FE issue) 

@bziondik we consider this as a different bug

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by andreluizmachado — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
