### PR TITLE
Temporary commented out, as provided a lot of side affects during nav…

### PR DESCRIPTION
**Pull request by boajer**
…igation
It temporary fix, need to investigate hot to keep working commented out feature ( refreshing the state of 'preview' button for newrly created item

### CODE REVIEW

**Comment by antoinerobin** [comment]
@krampstudio if you could have a look. It displays correctly the treeview but breaks the preview button refreshing

**Comment by boajer** [comment]
Now applied fix without breaking existing functionality

**Comment by krampstudio** [comment]
It works but it will cause side effects (here you ask the properties to reload when you leave the authoring). Instead ask to the properties to reload when you show them back.

1. remove the actionManager line from the qti creator code
2. Look at the section API (in tao/views/js/layout/section)
3. in taoItems/views/js/controller/items/edit.js 
         -> section.on shown reload the properties 
(history.back shows the section)

**Comment by boajer** [comment]
@krampstudio PR was updated, please take a look.

**Comment by krampstudio** [comment]
No, please just let `history.back()` in the QtiCreator.
To be sure it was working (I wasn't :S ) I've created this PR https://github.com/oat-sa/extension-tao-item/pull/136 you should try along with only history.back when you click on the button.

**Pull request merged**
