### PR TITLE
Fix: correct export assets with & in the asset path

### PR DESCRIPTION
**Pull request by Businesspunk**
# [TR-2929](https://oat-sa.atlassian.net/browse/TR-2929)

<General Information>

## How to test
Deployed environment Terre - http://test-tr-2929.playground.kitchen.it.taocloud.org:49831/
or
Local environment Terre - [composer.zip](https://github.com/oat-sa/extension-tao-itemqti/files/7769422/composer.zip)

1. Create Item with Graphic Interaction with a background image that has & in a title (for example [new-unsplash.zip](https://github.com/oat-sa/extension-tao-itemqti/files/7769450/new-unsplash.zip) )
2. Create a test with Item created in the first step
3. Export the test

In exported item, you should see no empty data attribute in the object
image

### CODE REVIEW

**Review by poyuki — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by roman-kovalev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by krampstudio — CHANGES_REQUESTED** [review]
The fix doesn't seem to work for me on the kitchen env:

image

**Review by krampstudio — APPROVED** [review]
The export is working fine, we will address the publishing in another PR

**Review by poyuki — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
