### PR TITLE
Fix/aut 445/do not save empty custom css

### PR DESCRIPTION
**Pull request by pnal**
https://oat-sa.atlassian.net/browse/AUT-445

How to test:
1. Save item with custom styles (use Style editor) - item XML should contain `<stylesheet href="style/custom/tao-user-styles.css" type="text/css" media="all" title="" />` and in item package should be `tao-user-styles.css` file
2. Clear all custom styles and save - item XML should NOT contain `<stylesheet href="style/custom/tao-user-styles.css" type="text/css" media="all" title="" />` and in item package should NOT be `tao-user-styles.css` file

### CODE REVIEW

**Review by bartlomiejmarszal — APPROVED** [review]
LGTM

**Review by bartlomiejmarszal — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by Silvia-loza — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-hanna.playground.kitchen.it.taocloud.org:40141/

**Pull request merged**
