### PR TITLE
fix: update QTI SDK to a version collecting a fix for AUT-245

### PR DESCRIPTION
**Pull request by pnal**
Update QTI-SDK to enable fix for [AUT-245](https://oat-sa.atlassian.net/browse/AUT-245)
The fix and more details about the issue can be found here: https://github.com/oat-sa/qti-sdk/pull/269

### CODE REVIEW

**Review by bartlomiejmarszal — APPROVED** [review]
LGTM

**Review by bartlomiejmarszal — CHANGES_REQUESTED** [review]
It's not fix it `chore`. No?

**Review by julien-sebire — CHANGES_REQUESTED** [review]
I suggest we upgrade `lib-tao-qti` to version `7.1.4` so that we also include support for `%` sign in `width` and `height` of `` tags. I'm sorry I didn't release it before. It's now available.

**Comment by julien-sebire** [comment]
I think fix is legit, because we're actually changing the code, even if it's by upgrading a library.
Chore would be for example a refactoring-only PR with no functional change.

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-nik.playground.kitchen.it.taocloud.org:48161/

**Comment by pnal** [comment]
> It's not fix it `chore`. No?
now there both, fix and chore in this PR
however I agree with Julien

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by bartlomiejmarszal — APPROVED** [review]
LGTM

**Pull request merged**
