### PR TITLE
[Fix] TAO 10227 - Response not updated after removed gap match

### PR DESCRIPTION
**Pull request by habemuscode**
**Related to**

https://oat-sa.atlassian.net/browse/TAO-10227

**Description**

If 1 answer is chosen for the gap match as a response it keeps remained after editing the answer in Response mode.
However, the user is able to edit the response if he sets 2 or more answers as a response for the gap match (please see the file gap_match_correct_behavior.gif in the Attachments).

**Steps to reproduce**

- Add Gap Match interaction to the canvas;
- Select a word and click the Magic Wand that appeared on the right of the Interaction;
- Click 'Response' in the interaction;
- Set the word to the gap and Save;
- Click Response in the interaction;
- Click the word in the gap to select it;
- Click the 'remove' (the arrow) button and Save;
- Click Response in the interaction;
- Click the word in the gap to select it.

**Actual result**

The edited response is not saved, the word remains in the gap.

**Expected result**

The word is removed from the gap.

### CODE REVIEW

**Review by adriloma — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

**Review by AndreyNegrov — APPROVED** [review]
Code review only

**Review by zagovorichev — CHANGES_REQUESTED** [review]
The case when we have 1 gap in the interaction doesn't work

**Comment by habemuscode** [comment]
@zagovorichev After trying different approaches, looks like you must need at least 1 item.

If not you get errors and can't open interaction again `TypeError: element.getSerial is not a function`

And if you see, when adding a new gap match interaction, one choice is by default

**Review by bziondik — CHANGES_REQUESTED** [review]
Have error
image

**Comment by habemuscode** [comment]
@zagovorichev @bziondik I push fix about the error when only one

**Review by bziondik — CHANGES_REQUESTED** [review]
I have failed test `taoQtiItem/views/js/test/qtiCreator/model/interactions/gapMatchInteraction/test.html` locally, please check
image

**Comment by habemuscode** [comment]
@bziondik `tao-enterprise-bosa/tao/views/build$ npx grunt connect:test taoqtiitemtest`

imagen

**Review by bziondik — APPROVED** [review]

**Pull request merged**
