### PR TITLE
Feature/AUT-208/Proper identifier validation in authoring UI

### PR DESCRIPTION
**Pull request by bziondik**
Related to: https://oat-sa.atlassian.net/browse/AUT-208

Unit test fail because of other issue - fix here https://github.com/oat-sa/extension-tao-itemqti/pull/1668/files
How to test:
- go to item Authoring
- add in `Identifier` forbidden symbol, for example`@` `=` `! `
- check warning in tooltip
- try to save item
- check warning message
- check the same errors for `Response` and `outcome Declaration`

image
image
image
image

### CODE REVIEW

**Review by ampaveliev — APPROVED** [review]
gj!

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by habemuscode — APPROVED** [review]
Great job!

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by bziondik** [comment]
@habemuscode @mike-ionut-mihai-sandu-tao added commit to fix case `However there’s another issue - for example there are several interactions in the item and one of them has invalid Response or Outcome ID. If the invalid interaction was removed, the item is still cannot be saved.`
Please, review again
Deployed to http://test-hanna.playground.kitchen.it.taocloud.org:40141/

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

**Review by 404passionFruit — COMMENTED** [review]
Tested on kitchen, there is no tooltip for me

**Review by 404passionFruit — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable) **playground**
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`
- [x] Pull request title and description are meaningful
- [x] Commits are following conventional commits

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-hanna.playground.kitchen.it.taocloud.org:40141/

**Pull request merged**
