### PR TITLE
Feature/ms 152/compile qti 22

### PR DESCRIPTION
**Pull request by julien-sebire**
This PR upgrades QTI-SDK to version 0.22.0 allowing compilation version management and gives a way to compile to a given version of QTI Compact.
Thorough tests have been done on the branch itself, along with the counterpart in extension-tao-testqti.

This PR is required by https://github.com/oat-sa/extension-tao-testqti/pull/1901

### CODE REVIEW

**Review by mike-ionut-mihai-sandu-tao — CHANGES_REQUESTED** [review]
bump version please

**Comment by julien-sebire** [comment]
Bumped version. Sorry for forgetting this... :)

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
looks good from my side
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by julien-sebire** [comment]
Not merged back in the days so outdated.

**Pull request closed without merging**
