### PR TITLE
Feature/tao 2659 stylesheets dispatch

### PR DESCRIPTION
**Pull request by ssipasseuth**

### CODE REVIEW

**Comment by no-chris** [comment]
I get the following error when removing all styles from a class. To reproduce: 
- open a class
- set a style
- save
- remove the style
- save

Invoking oat\unisa\controller\ItemsStyle::setItemClassStyles by http://pull-requests/mytao.rdf#superUser (GENERIS,CLEARRFW)
Get itemContent for item http://pull-requests/mytao.rdf#i1465979237211715 ()
php error(2): Invalid argument supplied for foreach() (PHPERROR)
	taoQtiItem/model/style/StyleService.php(116)             common_Logger::handlePHPErrors()
	taoQtiItem/model/style/StyleService.php(204)             oat\taoQtiItem\model\style\StyleService::addBodyStyles()
	unisa/controller/ItemsStyle.php(64)                      oat\taoQtiItem\model\style\StyleService::addClassBodyStyles()
	---                                                      oat\unisa\controller\ItemsStyle::setItemClassStyles()
	tao/models/classes/routing/ActionEnforcer.php(145)       call_user_func_array()
	tao/models/classes/routing/TaoFrontController.php(86)    oat\tao\model\routing\ActionEnforcer::execute()
	tao/models/classes/mvc/Bootstrap.php(395)                oat\tao\model\routing\TaoFrontController::legacy()
	tao/models/classes/mvc/Bootstrap.php(159)                oat\tao\model\mvc\Bootstrap::mvc()
	tao/models/classes/mvc/Bootstrap.php(211)                oat\tao\model\mvc\Bootstrap::dispatchHttp()
	index.php(31)                                            oat\tao\model\mvc\Bootstrap::dispatch()

**Comment by no-chris** [comment]
Other error. To reproduce:
- log out
- log in
- open a class 
- open the style panel
- clic save

Invoking oat\unisa\controller\ItemsStyle::setItemClassStyles by http://pull-requests/mytao.rdf#superUser (GENERIS,CLEARRFW)
Get itemContent for item http://pull-requests/mytao.rdf#i1465979235261611 ()
php error(2): Invalid argument supplied for foreach() (PHPERROR)
	taoQtiItem/model/style/StyleService.php(116)             common_Logger::handlePHPErrors()
	taoQtiItem/model/style/StyleService.php(204)             oat\taoQtiItem\model\style\StyleService::addBodyStyles()
	unisa/controller/ItemsStyle.php(64)                      oat\taoQtiItem\model\style\StyleService::addClassBodyStyles()
	---                                                      oat\unisa\controller\ItemsStyle::setItemClassStyles()
	tao/models/classes/routing/ActionEnforcer.php(145)       call_user_func_array()
	tao/models/classes/routing/TaoFrontController.php(86)    oat\tao\model\routing\ActionEnforcer::execute()
	tao/models/classes/mvc/Bootstrap.php(395)                oat\tao\model\routing\TaoFrontController::legacy()
	tao/models/classes/mvc/Bootstrap.php(159)                oat\tao\model\mvc\Bootstrap::mvc()
	tao/models/classes/mvc/Bootstrap.php(211)                oat\tao\model\mvc\Bootstrap::dispatchHttp()
	index.php(31)                                            oat\tao\model\mvc\Bootstrap::dispatch()
Get itemContent for item http://pull-requests/mytao.rdf#i1465979239448319 ()
php error(2): Invalid argument supplied for foreach() (PHPERROR)
	taoQtiItem/model/style/StyleService.php(116)             common_Logger::handlePHPErrors()
	taoQtiItem/model/style/StyleService.php(204)             oat\taoQtiItem\model\style\StyleService::addBodyStyles()
	unisa/controller/ItemsStyle.php(64)                      oat\taoQtiItem\model\style\StyleService::addClassBodyStyles()
	---                                                      oat\unisa\controller\ItemsStyle::setItemClassStyles()
	tao/models/classes/routing/ActionEnforcer.php(145)       call_user_func_array()
	tao/models/classes/routing/TaoFrontController.php(86)    oat\tao\model\routing\ActionEnforcer::execute()
	tao/models/classes/mvc/Bootstrap.php(395)                oat\tao\model\routing\TaoFrontController::legacy()
	tao/models/classes/mvc/Bootstrap.php(159)                oat\tao\model\mvc\Bootstrap::mvc()
	tao/models/classes/mvc/Bootstrap.php(211)                oat\tao\model\mvc\Bootstrap::dispatchHttp()
	index.php(31)                                            oat\tao\model\mvc\Bootstrap::dispatch()
Get itemContent for item http://pull-requests/mytao.rdf#i1465979235261611 ()
Get itemContent for item http://pull-requests/mytao.rdf#i1465979239448319 ()
Invoking taoItems_actions_Items::editItem by http://pull-requests/mytao.rdf#superUser (GENERIS,CLEARRFW)
Missing or invalid parameter uri (tao_models_classes_MissingRequestParameterException)
System Error: uncaught exception (tao_models_classes_MissingRequestParameterException) in (/tao/pull-requests/tao/actions/class.RdfController.php) at line 125: Missing or invalid parameter uri ()
	tao/models/classes/mvc/Bootstrap.php(289)   common_Logger::e()
	tao/models/classes/mvc/Bootstrap.php(175)   oat\tao\model\mvc\Bootstrap::catchError()
	tao/models/classes/mvc/Bootstrap.php(211)   oat\tao\model\mvc\Bootstrap::dispatchHttp()
	index.php(31)                               oat\tao\model\mvc\Bootstrap::dispatch()

**Comment by ssipasseuth** [comment]
Hi, I fixed both issues, please review again

**Comment by no-chris** [comment]
I double checked that I had all the last commits from all related repos, cleared my browser cache, did a fresh install, but still have some similar troubles, although not exactly the sames.

- Create a class
- put 2 items in it
- Open style panel
- clic save
=> error. it works if the class has no item in it.

- in the same class
- select a style
- clic save
=> ok
- unselect class
- clic save
=> error

**Pull request merged**
