### PR TITLE
Fix/tr 830/associate interaction display results area

### PR DESCRIPTION
**Pull request by lecosson**
Related to: https://oat-sa.atlassian.net/browse/TR-830

remove `display: none` rule for associate interaction result area elements, require changes in `oat-sa/tao-item-runner-qti-fe`

Requires: 
 - [ ] https://github.com/oat-sa/tao-item-runner-qti-fe/pull/172

### CODE REVIEW

**Review by jsconan — CHANGES_REQUESTED** [review]
It would be nice to have the package.json file update with the branch targeting the companion PR.

However, since the companion PR contains a small issue with npm, I was unable to test the feature. The code looks ok, but I cannot validate without checking the behavior.

Moreover, the bundle should not be updated yet:
- the package.json does not reference the correct version with respect to the companion PR
- the generated bundle may change once the companion PR will be merged and the corresponding package published.
Actually, it is generated upon release, so no need to add it on every PR. Regarding the CSS this is different.

**Comment by lecosson** [comment]
> * the package.json does not reference the correct version with respect to the companion PR

added

**Review by jsconan — APPROVED** [review]
It works well. GJ!

Note: once the companion PR will be merged, when applying the new version please pay attention to the package lock file. It must not reference the github repo but the npm registry.

image

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by wazelin — COMMENTED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

Will approve once the finalized dependency version is set.

**Review by wazelin — APPROVED** [review]

**Pull request merged**
