### PR TITLE
do not render empty value

### PR DESCRIPTION
**Pull request by hutnikau**
related to:
https://github.com/oat-sa/extension-tao-itemqti/pull/504

### CODE REVIEW

**Comment by ssipasseuth** [comment]
why there is no need to update the template on the server as for https://github.com/oat-sa/extension-tao-itemqti/pull/504 ?

**Comment by hutnikau** [comment]
mpdeploy branch has different template on the server side.

**Comment by ssipasseuth** [comment]
not sure I understand, do you mean https://github.com/oat-sa/extension-tao-itemqti/blob/TAO-1914_record_response_type_mpdeploy/model/qti/templates/qti.responseDeclaration.tpl.php ? It is identical in both develop and mpdeploy branches.

**Comment by hutnikau** [comment]
No, it is not identical:
https://github.com/oat-sa/extension-tao-itemqti/blob/mpdeploy/model/qti/templates/qti.responseDeclaration.tpl.php
https://github.com/oat-sa/extension-tao-itemqti/blob/develop/model/qti/templates/qti.responseDeclaration.tpl.php

**Comment by ssipasseuth** [comment]
So is it alright that mpdeploy won't support record type correct response declaration for now ?

**Pull request merged**
